import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Define your stocks
stocks = ["3MINDIA.NS","AARTIIND.NS","ABB.NS","ABBOTINDIA.NS","ABCAPITAL.NS","ABFRL.NS","ACC.NS","ADANIENT.NS",
"ADANIGREEN.NS","ADANIPORTS.NS","ADANIPOWER.NS","ADANITRANS.NS","AIAENG.NS","AIRTEL.NS","ALKEM.NS",
"AMBUJACEM.NS","APOLLOHOSP.NS","APOLLOTYRE.NS","ASHOKLEY.NS","ASIANPAINT.NS","ASTRAL.NS","ATGL.NS",
"AUBANK.NS","AUROPHARMA.NS","AXISBANK.NS","BAJAJ-AUTO.NS","BAJAJFINSV.NS","BAJAJHLDNG.NS","BAJAJFINANCE.NS",
"BALKRISIND.NS","BALRAMCHIN.NS","BANDHANBNK.NS","BANKBARODA.NS","BANKINDIA.NS","BERGEPAINT.NS","BEL.NS",
"BHEL.NS","BIOCON.NS","BOSCHLTD.NS","BPCL.NS","BRITANNIA.NS","CADILAHC.NS","CANBK.NS","CANFINHOME.NS",
"CHOLAFIN.NS","CIPLA.NS","COALINDIA.NS","COFORGE.NS","COLPAL.NS","CONCOR.NS","COROMANDEL.NS","CROMPTON.NS",
"CUB.NS","CUMMINSIND.NS","DABUR.NS","DALBHARAT.NS","DEEPAKNTR.NS","DIVISLAB.NS","DLF.NS","DRREDDY.NS",
"EICHERMOT.NS","ESCORTS.NS","EXIDEIND.NS","FEDERALBNK.NS","GAIL.NS","GLAND.NS","GMRINFRA.NS","GODREJCP.NS",
"GODREJPROP.NS","GRANULES.NS","GRASIM.NS","GUJGASLTD.NS","HAVELLS.NS","HCLTECH.NS","HDFC.NS",
"HDFCAMC.NS","HDFCBANK.NS","HDFCLIFE.NS","HEROMOTOCO.NS","HINDALCO.NS","HINDPETRO.NS","HINDUNILVR.NS",
"ICICIBANK.NS","ICICIGI.NS","ICICIPRULI.NS","IDEA.NS","IDFCFIRSTB.NS","IEX.NS","IGL.NS","INDHOTEL.NS",
"INDIGO.NS","INDUSINDBK.NS","INDUSTOWER.NS","INFY.NS","IOC.NS","IPCALAB.NS","IRCTC.NS","ITC.NS",
"JINDALSTEL.NS","JSWSTEEL.NS","JUBLFOOD.NS","KOTAKBANK.NS","LALPATHLAB.NS","LAURUSLABS.NS","LICHSGFIN.NS",
"LT.NS","LTTS.NS","LTI.NS","LUPIN.NS","M&M.NS","M&MFIN.NS","MANAPPURAM.NS","MARICO.NS","MARUTI.NS",
"MGL.NS","MINDTREE.NS","MPHASIS.NS","MRF.NS","MUTHOOTFIN.NS","NATIONALUM.NS","NAUKRI.NS","NAVINFLUOR.NS",
"NESTLEIND.NS","NMDC.NS","NTPC.NS","OBEROIRLTY.NS","OFSS.NS","ONGC.NS","PAGEIND.NS","PEL.NS","PETRONET.NS",
"PFC.NS","PIDILITIND.NS","PIIND.NS","PNB.NS","POLYCAB.NS","POWERGRID.NS","PVR.NS","RBLBANK.NS","RECLTD.NS",
"RELAXO.NS","RELIANCE.NS","SAIL.NS","SBICARD.NS","SBILIFE.NS","SBIN.NS","SHREECEM.NS","SIEMENS.NS",
"SRF.NS","SRTRANSFIN.NS","SUNPHARMA.NS","SYNGENE.NS","TATACHEM.NS","TATACONSUM.NS","TATAMOTORS.NS",
"TATAPOWER.NS","TATASTEEL.NS","TCS.NS","TECHM.NS","TITAN.NS","TORNTPHARM.NS","TORNTPOWER.NS","TRENT.NS",
"TVSMOTOR.NS","UBL.NS","ULTRACEMCO.NS","UPL.NS","VBL.NS","VEDL.NS","VOLTAS.NS","WIPRO.NS","ZEEL.NS",
"ZYDUSLIFE.NS"]

# Download data
data = yf.download(stocks, start='2020-01-01', end='2025-01-01',progress=False)['Close']
data = data.dropna(axis=1, how='all')

# Forward fill missing data (preferred syntax now)
data = data.ffill().dropna()

# Calculate daily returns
returns = data.fillna(method='ffill').pct_change().dropna()
correlation_matrix = returns.corr()
print(correlation_matrix)
print(correlation_matrix.shape)
#Visualize
#plt.figure(figsize=(10, 6))
#sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', center=0)
#plt.title('Stock Return Correlation Matrix')
#plt.show()
